/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Helmet } from 'react-helmet-async';
import { styled } from '@mui/material/styles';
import PostFrame from 'src/components/PostFrame/PostFrame';

const TypeQuest = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(250, 250, 250, 1)`,
  boxShadow: `0px 4px 8px rgba(0, 0, 0, 0.16)`,
  borderRadius: `8px`,
  display: `grid`,
  position: `relative`,
  isolation: `isolate`,
  height: `auto`,
  width: `100%`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
  gridTemplateColumns: `repeat(auto-fit, minmax(390px, 1fr))`,
  columnGap: `10px`,
  rowGap: `10px`,
}));

const PostFrame1 = styled(PostFrame)(({ theme }) => ({
  height: `478px`,
  width: `390px`,
  margin: `0px`,
}));

function Card19D3(props) {
  return (
    <TypeQuest className={props.className}>
      <Helmet>
        <title>Card19D3</title>
      </Helmet>
      {props.posts &&
        props.posts.map((mypost, index) => {
          return <PostFrame1 key={index} post={props.posts[index]} />;
        })}
    </TypeQuest>
  );
}

export default Card19D3;
